# constants.py

import pygame
import math

# --- Screen & World ---
pygame.init()
info = pygame.display.Info()
SCREEN_WIDTH = info.current_w
SCREEN_HEIGHT = info.current_h
pygame.quit()

CENTER_X = SCREEN_WIDTH // 2
CENTER_Y = SCREEN_HEIGHT // 2
WORLD_BOUNDS = 2000

# --- Colors ---
WHITE = (255, 255, 255)
PLAYER2_COLOR = pygame.Color("#F4A261") # Sandy Orange
BLACK = (0, 0, 0)
RED = (231, 111, 81)
YELLOW = (233, 196, 106)
GRAY = (150, 150, 150)
OPTIMAL_SAIL_COLOR = (0, 200, 255, 150)
SAIL_COLOR = (245, 245, 245)
WAKE_COLOR = (220, 235, 255)
MAP_BG_COLOR = (0, 69, 107, 180)
MAP_BORDER_COLOR = (200, 200, 200)
MAP_BOAT_COLOR = (233, 196, 106)
BUTTON_COLOR = pygame.Color("#264653")
BUTTON_HOVER_COLOR = pygame.Color("#2A9D8F")
BUTTON_TEXT_COLOR = WHITE
BUOY_COLOR = pygame.Color("#E76F51")
START_FINISH_BUOY_COLOR = pygame.Color("#F4A261")
START_FINISH_LINE_COLOR = WHITE
NEXT_BUOY_INDICATOR_COLOR = (0, 255, 0)
HUD_BG_COLOR = (0, 0, 0, 100)

# --- NEW Lighter Pastel Ocean Palette ---
# Base deep ocean color
DARK_BLUE = pygame.Color("#4A90E2")
# Lighter shades for the shallows around sandbars
DEPTH_COLORS = [pygame.Color("#55A6D9"), pygame.Color("#78C2C4")]
# Even lighter shades for the shallowest areas
SHALLOW_COLORS = [pygame.Color("#A2D5F2"), pygame.Color("#BDE4F4")]
# Colors for the sandbars themselves
SAND_COLOR = pygame.Color("#F9ECCB")  # Light sandy beige
DARK_SAND_COLOR = pygame.Color("#E5D8B3") # Darker sandy color for borders/minimap
LIGHT_BLUE = (173, 216, 230) # A lighter, more visible blue for waves


# --- Boat Properties ---
BOAT_TURN_SPEED = 2.5
BOAT_ACCEL_FACTOR = 0.08
BOAT_DRAG = 0.985
BOAT_COLLISION_SPEED_REDUCTION = 0.95
SANDBAR_DRAG_MULTIPLIER = 25.0
NO_POWER_DECEL = 0.75
MAX_BOAT_SPEED = 15.0
MIN_TURN_EFFECTIVENESS = 0.15
SAIL_TRIM_SPEED = 1.5
MAX_SAIL_ANGLE_REL = 85
SAIL_LENGTH = 35
SAIL_MAX_CURVE = 8
MIN_SAILING_ANGLE = 45
OPTIMAL_INDICATOR_LENGTH = 25
NUM_AI_BOATS = 4
AI_BOAT_COLORS = [
    pygame.Color("#E63946"),
    pygame.Color("#F4A261"),
    pygame.Color("#2A9D8F"),
    pygame.Color("#457B9D"),
]


# --- Wind Properties ---
MIN_WIND_SPEED = 10.0
MAX_WIND_SPEED = 24.0
WIND_SPEED_CHANGE_RATE = 0.2
WIND_DIR_CHANGE_RATE = 0.6
WIND_UPDATE_INTERVAL = 200

# --- Environment Properties ---
NUM_WAVE_LAYERS = 3
WAVE_LAYER_ALPHA = 60 # Increased for more visibility
WAVE_LINE_THICKNESS = 1
WAVE_SCROLL_SPEED_BASE = [0.4, 0.6, 0.8]
WAVE_DENSITY = 150
NUM_SANDBARS = 25 # More sandbars for a richer world
MIN_SANDBAR_SIZE = 80
MAX_SANDBAR_SIZE = 250
MIN_SANDBAR_VERTICES = 7
MAX_SANDBAR_VERTICES = 12
SANDBAR_RADIUS_VARIATION = 0.4
MIN_OBJ_SEPARATION = 150

# --- Wake Properties ---
MAX_WAKE_PARTICLES = 150
WAKE_SPAWN_INTERVAL = 0.04
WAKE_LIFETIME = 2.0
WAKE_START_SIZE = 5
WAKE_END_SIZE = 1

# --- Course & Race Properties ---
DEFAULT_RACE_LAPS = 3
NUM_COURSE_BUOYS = 3
START_FINISH_LINE = [(-100, -150), (-100, 150)]
START_FINISH_NORMAL = (1, 0)
START_FINISH_WIDTH = 10
BUOY_RADIUS = 15
BUOY_ROUNDING_RADIUS = 40
LINE_CROSSING_DEBOUNCE = 1.0
POINTS_AWARDED = [5, 4, 3, 2, 1, 0]

# --- UI Properties ---
MAP_WIDTH = 150
MAP_HEIGHT = 150
MAP_MARGIN = 10
WIND_GAUGE_RADIUS = 40
WIND_GAUGE_POS = (WIND_GAUGE_RADIUS + 20, WIND_GAUGE_RADIUS + 20)
PAUSE_MENU_WIDTH = 300
PAUSE_MENU_HEIGHT = 250
PAUSE_BUTTON_WIDTH = 200
PAUSE_BUTTON_HEIGHT = 40
WIND_BUTTON_MARGIN = 10

# UI Rects
MAP_RECT_P1 = pygame.Rect(SCREEN_WIDTH - MAP_WIDTH - MAP_MARGIN, MAP_MARGIN, MAP_WIDTH, MAP_HEIGHT)
MAP_RECT_P2 = pygame.Rect(SCREEN_WIDTH - MAP_WIDTH - MAP_MARGIN, SCREEN_HEIGHT // 2 + MAP_MARGIN, MAP_WIDTH, MAP_HEIGHT)
WIND_BUTTON_RECT = pygame.Rect(WIND_BUTTON_MARGIN, 70, 120, 30)
SETUP_BUTTON_WIDTH = 150
SETUP_BUTTON_HEIGHT = 40
LAP_BUTTON_SIZE = 30

MAP_WORLD_SCALE_X = MAP_WIDTH / (2 * WORLD_BOUNDS)
MAP_WORLD_SCALE_Y = MAP_HEIGHT / (2 * WORLD_BOUNDS)
MAP_SANDBAR_MARKER_RADIUS = 3
MAP_BUOY_MARKER_RADIUS = 4
MAP_BOAT_MARKER_SIZE = 5
MAP_AI_BOAT_COLOR = (210, 210, 210)

# Pause Menu Buttons
RESUME_BUTTON_RECT = pygame.Rect(CENTER_X - PAUSE_BUTTON_WIDTH // 2, CENTER_Y - 90, PAUSE_BUTTON_WIDTH, PAUSE_BUTTON_HEIGHT)
RESTART_BUTTON_RECT = pygame.Rect(CENTER_X - PAUSE_BUTTON_WIDTH // 2, CENTER_Y - 30, PAUSE_BUTTON_WIDTH, PAUSE_BUTTON_HEIGHT)
FORFEIT_RACE_BUTTON_RECT = pygame.Rect(CENTER_X - PAUSE_BUTTON_WIDTH // 2, CENTER_Y + 30, PAUSE_BUTTON_WIDTH, PAUSE_BUTTON_HEIGHT)
EXIT_GAME_BUTTON_RECT = pygame.Rect(CENTER_X - PAUSE_BUTTON_WIDTH // 2, CENTER_Y + 90, PAUSE_BUTTON_WIDTH, PAUSE_BUTTON_HEIGHT)

# End Screen Buttons
MAIN_MENU_BUTTON_RECT = pygame.Rect(CENTER_X - SETUP_BUTTON_WIDTH // 2, SCREEN_HEIGHT * 0.8, SETUP_BUTTON_WIDTH, SETUP_BUTTON_HEIGHT)
EXIT_END_SCREEN_BUTTON_RECT = pygame.Rect(CENTER_X - SETUP_BUTTON_WIDTH // 2, SCREEN_HEIGHT * 0.8 + 50, SETUP_BUTTON_WIDTH, SETUP_BUTTON_HEIGHT)

# --- Debug ---
DEBUG_SAIL_ANGLES = False
