# constants.py

import pygame
import math

# --- Screen & World ---
# Initialize Pygame temporarily to get screen info
pygame.init()
info = pygame.display.Info()
# Set the screen size to the current monitor's resolution
SCREEN_WIDTH = info.current_w
SCREEN_HEIGHT = info.current_h
pygame.quit() # Quit the temporary instance

CENTER_X = SCREEN_WIDTH // 2
CENTER_Y = SCREEN_HEIGHT // 2
WORLD_BOUNDS = 2000

# --- Colors ---
WHITE = (255, 255, 255)
PLAYER2_COLOR = pygame.Color("#F4A261") # Sandy Orange
BLACK = (0, 0, 0)
RED = (231, 111, 81)
YELLOW = (233, 196, 106)
GRAY = (150, 150, 150)
OPTIMAL_SAIL_COLOR = (0, 200, 255, 150)
SAIL_COLOR = (245, 245, 245)
WAKE_COLOR = (200, 220, 255)
MAP_BG_COLOR = (0, 69, 107, 180) # Darker sea blue for UI
MAP_BORDER_COLOR = (200, 200, 200)
MAP_BOAT_COLOR = (233, 196, 106)
BUTTON_COLOR = pygame.Color("#264653")
BUTTON_HOVER_COLOR = pygame.Color("#2A9D8F")
BUTTON_TEXT_COLOR = WHITE
BUOY_COLOR = pygame.Color("#E76F51")
START_FINISH_BUOY_COLOR = pygame.Color("#F4A261")
START_FINISH_LINE_COLOR = WHITE
NEXT_BUOY_INDICATOR_COLOR = (0, 255, 0)

# Ocean-themed pastel palette
BLUE = pygame.Color("#A8DADC") # Base ocean color
DARK_BLUE = pygame.Color("#1D3557") # Deepest ocean for the base fill
DEPTH_COLORS = [pygame.Color("#457B9D"), pygame.Color("#A8DADC")]
SHALLOW_COLORS = [pygame.Color("#2A9D8F"), pygame.Color("#E9C46A")]
SAND_COLOR = pygame.Color("#F1FAEE") # Lightest shallow areas/sand
DARK_SAND_COLOR = pygame.Color("#A8DADC")
LIGHT_BLUE = (100, 150, 200) # Original light blue for waves


# --- Boat Properties ---
BOAT_TURN_SPEED = 2.0
BOAT_ACCEL_FACTOR = 0.08
BOAT_DRAG = 0.985
BOAT_COLLISION_SPEED_REDUCTION = 0.95
SANDBAR_DRAG_MULTIPLIER = 25.0
NO_POWER_DECEL = 0.75
MAX_BOAT_SPEED = 15.0
MIN_TURN_EFFECTIVENESS = 0.15
SAIL_TRIM_SPEED = 1.0
MAX_SAIL_ANGLE_REL = 85
SAIL_LENGTH = 35
SAIL_MAX_CURVE = 8
MIN_SAILING_ANGLE = 45
OPTIMAL_INDICATOR_LENGTH = 25
NUM_AI_BOATS = 4
AI_BOAT_COLORS = [
    pygame.Color("#E63946"), # Red
    pygame.Color("#F4A261"), # Orange
    pygame.Color("#2A9D8F"), # Green
    pygame.Color("#457B9D"), # Blue
]


# --- Wind Properties ---
MIN_WIND_SPEED = 10.0
MAX_WIND_SPEED = 24.0
WIND_SPEED_CHANGE_RATE = 0.2
WIND_DIR_CHANGE_RATE = 0.6
WIND_UPDATE_INTERVAL = 200

# --- Environment Properties ---
NUM_WAVE_LAYERS = 3
WAVE_LAYER_ALPHA = 40 # Reduced alpha for subtlety
WAVE_LINE_THICKNESS = 1
WAVE_SCROLL_SPEED_BASE = [0.4, 0.6, 0.8]
WAVE_DENSITY = 100
NUM_SANDBARS = 15
MIN_SANDBAR_SIZE = 60
MAX_SANDBAR_SIZE = 200
MIN_SANDBAR_VERTICES = 7
MAX_SANDBAR_VERTICES = 12
SANDBAR_RADIUS_VARIATION = 0.4
MIN_OBJ_SEPARATION = 150

# --- Wake Properties ---
MAX_WAKE_PARTICLES = 100
WAKE_SPAWN_INTERVAL = 0.05
WAKE_LIFETIME = 1.5
WAKE_START_SIZE = 4
WAKE_END_SIZE = 1

# --- Course & Race Properties ---
DEFAULT_RACE_LAPS = 3
NUM_COURSE_BUOYS = 3
START_FINISH_LINE = [(-100, -150), (-100, 150)]
START_FINISH_NORMAL = (1, 0)
START_FINISH_WIDTH = 10
BUOY_RADIUS = 15
BUOY_ROUNDING_RADIUS = 40
LINE_CROSSING_DEBOUNCE = 1.0
POINTS_AWARDED = [5, 4, 3, 2, 1, 0] # Points for 1st, 2nd, etc.

# --- UI Properties ---
MAP_WIDTH = 150
MAP_HEIGHT = 150
MAP_MARGIN = 10
WIND_GAUGE_RADIUS = 40
WIND_GAUGE_POS = (WIND_GAUGE_RADIUS + 20, WIND_GAUGE_RADIUS + 20)


# UI Rects
MAP_RECT_P1 = pygame.Rect(SCREEN_WIDTH - MAP_WIDTH - MAP_MARGIN, MAP_MARGIN, MAP_WIDTH, MAP_HEIGHT)
MAP_RECT_P2 = pygame.Rect(SCREEN_WIDTH - MAP_WIDTH - MAP_MARGIN, SCREEN_HEIGHT // 2 + MAP_MARGIN, MAP_WIDTH, MAP_HEIGHT)

MAP_WORLD_SCALE_X = MAP_WIDTH / (2 * WORLD_BOUNDS)
MAP_WORLD_SCALE_Y = MAP_HEIGHT / (2 * WORLD_BOUNDS)
MAP_SANDBAR_MARKER_RADIUS = 3
MAP_BUOY_MARKER_RADIUS = 4
MAP_BOAT_MARKER_SIZE = 5
MAP_AI_BOAT_COLOR = (210, 210, 210)
WIND_BUTTON_WIDTH = 120
WIND_BUTTON_HEIGHT = 30
WIND_BUTTON_MARGIN = 10
WIND_BUTTON_RECT = pygame.Rect(WIND_BUTTON_MARGIN, 70, WIND_BUTTON_WIDTH, WIND_BUTTON_HEIGHT)
SETUP_BUTTON_WIDTH = 150
SETUP_BUTTON_HEIGHT = 40
LAP_BUTTON_SIZE = 30

# --- Debug ---
DEBUG_SAIL_ANGLES = False
